version: '3'

services:
  frontend:
    build:
      context: ./daily_diet
    ports:
      - "3000:3000"
    volumes:
      - ./daily_diet:/app

  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres

volumes:
  postgres_data:  
